### ISSUE TITLE
Tinker pdbxyz does not take key file into account

### ISSUE THREAD

**Issue by zhi-wang** [TinkerTools/tinker#103]
### Discussed in https://github.com/TinkerTools/tinker9/discussions/188

<div type='discussions-op-text'>

<sup>Originally posted by **lukaszmilewski** March 24, 2022</sup>
Hi,

i have an issue with pdbxyz tool.

Tinker pdbxyz does not take key file into account. 

I am using the command:
`pdbxyz my-file.pdb -key tinker.key`

tinker.key file inside:
#forcefield
parameters /home/users/lmilewski/programs/force_field/charmm27.prm

The output is the same as default without key file (not this force field). Atom types are not corresponding with charmm27 force field.
What can I do to use force field which is not the default one?

Thanks for your help!</div>

**Comment by pren** [comment]
Try to copy the prm to your current dir and use "parameters charmm27"
Is this prm file from a very old tinker distribution?

**Comment by jayponder** [comment]
Pengyu is correct just above. We have not distributed a parameter file named "charmm27" for many years. The CHARMM people briefly renamed their charmm22 protein parameter as charmm27, so we did the same with Tinker. The actual parameter values are the same. So you must be using a very old version of TInker, and my first suggestion is for you to update to a current version.

It is also possible that there is some issue with your PDB file; perhaps some unusual item or feature that confuses the PDBXYZ program such that it doesn't think your structure is a "protein". Please post the PDB file, and we can take a look to see what is causing your issue.

**Comment by jayponder** [comment]
Thanks for sending me the PDB file via email. I was able to translate it to a Tinker "xyz" file using the PDBXYZ program and the "charmm22.prm" parameter file distributed with the current version of Tinker.

Please get and build the current Tinker from here on Github, as I did patch a small issue with the "unusual" residue name that your Gromacs-generated PDB file used for the sodium ions.

The converted PDB file as the compressed Tinker "xyz" file is attached here:

[md.xyz.gz](https://github.com/TinkerTools/tinker/files/8359426/md.xyz.gz)
