### ISSUE TITLE
Tinker-OpenMM Type Error

### ISSUE THREAD

**Issue by emleddin** [TinkerTools/tinker#106]
Hello!

When trying to compile Tinker-OpenMM from the latest commit ([b6a7ccc](https://github.com/TinkerTools/tinker/commit/b6a7ccc26a40f24fb43b8e5e21aad935ffb8c1fa)) and [OpenMM 7.5.0](https://github.com/openmm/openmm/commit/b49b82efb5a253a7c891ca084b3370e181de2ea3), I ran into the following error:

```
gfortran -c -Ofast -msse3 -fopenmp ommdata.f -o ommdata.o
ommdata.f:169:49:

  169 |      &                      w4scale,w5scale,udiag,polprt,dpequal,
      |                                                 1
Error: Symbol ‘udiag’ at (1) has no IMPLICIT type; did you mean ‘udir’?
make: *** [Makefile:736: ommdata.o] Error 1
```

I was able to get past this error by changing all instances of `udiag` in `ommstuf.cpp` and `ommdata.f` to `uaccel` (to match the `polpot` module). I'm not exactly sure if this is specific to my own system, which is why I'm raising the issue.

I also noticed that the `openmm/Makefile` header specifies to use `make install` to put the executables in the bin, but the rule is actually `rename`.

---
Compilation Details:
- Ubuntu 20.04
- Cuda 11.5 (through the nvhpc toolkit)
- CMake 3.22.1
- GCC 9.3.0
- SWIG 4.0.1

**Comment by jayponder** [comment]
We are sorry, but as of right now Tinker-OpenMM is not supported. Please see the notice posted on the main page at https://github.com/TinkerTools/tinker-openmm/. We may try to get Tinker-OpenMM working again with current OpenMM in the future, but there is no firm timetable for doing this. The AMOEBA force field should work correctly in current OpenMM via the standard OpenMM interfaces.

If you wish to use Tinker-style files the setup or the AMOEBA and related force fields on GPUs, you can also use the Tinker9 or Tinker-HP codes that are available from the https://github.com/TinkerTools/ site.
