### ISSUE TITLE
OPLSAA parametrization of docked hit

### ISSUE THREAD

**Issue by eneas77** [TinkerTools/tinker#107]
HI all,

I´d like to run a post-docking refinement udner OPLS-AA scheme. Receptor is succesfully parametrized via pdbxyz, but trying to run pdbxyz on the ligand with the .key file pointing to the oplsaa.prm library doesn´t parametrize the ligand at all.

Is Tinker right now capable to parametrize a ligand under OPLS-AA scheme? Any outsource way to make it?

Thank you kidnly,

E77

**Comment by jayponder** [comment]
Use the LigParGen automated parameter generator for OPLS-AA. You can find it on the Jorgensen group's web site at zarbi.chem.yale.edu/ligpargen/. LigParGen writes out OPLS-AA parameters for an input organic ligand in many formats, including Tinker format. You will probably need to renumber the atom types from the LigParGen output so those type numbers do not conflict those for the protein receptor. There is a PRMEDIT program as part of Tinker that will change the numbers of the ligand types for you, then you can just add the ligand parameters to your .key file.

**Comment by eneas77** [comment]
Thanks for this ;-).
LigParGen website is capable to yield .xyz/.key files. However, after succesfully trying the command-line tool, there is no similar .xyz/.key files for this. Main article (https://academic.oup.com/nar/article/45/W1/W331/3747780?login=true) doesn´t refer to this type of Tinker files.

I´m trying to parametrize 200 molecules, and obviously the server for this is not efficient. Does anyone in the forum have a similar issue of parametrizing a large set of molecules?

A point of advice: I´d also appreciate not closing any githup issue until a satisfactory reply is met. Rushing to closing the issue without a feedback from the individual who posted it seems dodgy.

Thank you very much,

E77

**Comment by eneas77** [comment]
Thanks for this. https://github.com/Isra3l/ligpargen/ definetely work. The issue came from an old version of LigParGen, which is the one pointed from the LigParGen server. Something the developers should fix.

Thanks again.

E77

**Comment by jayponder** [comment]
You should post something on the LigParGen GitHub site, or email the Jorgensen group. I'm sure they would be happy to update the link on the server site, and this has just slipped through past their attention.

Please keep in mind the people providing these codes, servers, etc. are generally academic scientists, who often can't get support to provide such items as it's not "research". They are often doing this work in their "spare time" to be of service to the broader community. When you find an issue, please gently point it out to the right folks, and try to help the cause.
