### ISSUE TITLE
save-force command

### ISSUE THREAD

**Issue by vojtechkostal** [TinkerTools/tinker#114]
Hi,

I would like to follow the force components on each atom during the molecular dynamics run. However, the keyword "save-force" appends the same values in each dynamics step. I observe this issue only using GPU via OpenMM interface. Could you please advise me how to get the forces in each step properly?

Thanks in advance!

**Comment by jayponder** [comment]
This is the same comment I left to your similar question under the Tinker-OpenMM repository:

Tinker-OpenMM is no longer supported as of March 2021, as is noted on the main page for the repository, located at https://github.com/TinkerTools/tinker-openmm/. The "save-force" option is only available from Tinker-enabled code such as Tinker-OpenMM, and (probably, not sure?) is not availabel from the native OpenMM interface to AMOEBA.

We still plan to try to update and fix Tinker-OpenMM at some point, but this is a fairly big task and is currently not being worked on. In the meantime, you can run AMOEBA on GPUs using either the Tinker9 or the Tinker-HP codes available from https://github.com/TinkerTools/. Note that saving forces and other similar things can really hurt the simulation speed when running on GPUs. For this reason, some of these kinds of saving options are often not available in GPU codes.

Finally, you could always use the CPU version of Tinker (a.k.a., Tinker8) which definitely supports the "save-force" keyword, but will of course be much slower.
