### ISSUE TITLE
Calculate elastic modulus

### ISSUE THREAD

**Issue by libaiiiii** [TinkerTools/tinker#117]
I am a new who just started learning Tinker. I want to calculate the elastic modulus of the crystal structure.  However I didn't find any examples or commands for calculating the elastic modulus. So how do I calculate the modulus of elasticity?

**Comment by jayponder** [comment]
Hi, This calculation is not included in any of the Tinker routines, and is not planned for future inclusion. So you will need to write your own code or methods outside of Tinker to compute the modulus of elasticity.
