### ISSUE TITLE
 neutral amino acid parameters in unpolarized force fields（eg. amber ,charmm)

### ISSUE THREAD

**Issue by Wodnerstruck** [TinkerTools/tinker#122]
Hi!
I am using tinker's protein program to build amino acids or peptides and use analyze for energy calculation, when using non-polarized force fields (such as amber, charmm), neutral amino acid residues like ASH and GLH do not have corresponding atomic parameters, how should I solve this problem? Is there any hope that the latest aber force field parameters will be updated in Tinker? Thanks!

**Comment by jayponder** [comment]
Unfortunately, if you need ASH or GLH parameters, then you will need to add them to the Tinker files yourself after finding the corresponding parameters in the actual Amber or CHARMM parameter files. This is actually not too hard to do if you have access to the Amber and CHARMM files.

We do intend to update the Amber and CHARMM parameters distributed with Tinker to more recent versions, but there is no current time frame for doing this.
