### ISSUE TITLE
Issue with AMOEBA 

### ISSUE THREAD

**Issue by razinzafran** [TinkerTools/tinker#124]
Hye everyone. I'm a final year student in my university. I currently doing my final year project which involves the usage of tinker. I had no idea on the essential of tinker because I've been following what's my supervisor shown me. My project is about benchmarking the AMOEBA force field in determining the static dielectric constant value for various solvents. I'm at the analysis stage of my project and had to tabulate the dipole moment of each frame in order to calculate the static dielectric constant values. My issue is, when is use the 'analyze' tool in tinker and choose M, its print out the dipole moment magnitude that is zero for each frame.  My molecule is polar so I didn't understand why it have zero magnitude of dipole moment. I've search for a solution but didn't find any. Is there any solution to this? Please help me to solve this problem @jayponder

**Comment by jayponder** [comment]
There must be something wrong with your simulation setup (ie, likely with the "key" file used). If this is still an open issue, please send email to ponder@dasher.wustl.edu with details, and sample trajectory and key files. This is impossible to debug from just the description you have provided above.
