### ISSUE TITLE
Issue with xyz file generated from PDB file with Phosphoserine

### ISSUE THREAD

**Issue by BJWiley233** [TinkerTools/tinker#127]
Hi,

I am hoping to run minimization and MD on a phoshorylated ERK structure I created using 2 singly phosphorylated serines on a model I threaded.  I can run `pdbxyz` correctly using the `SEP` residue name, the  `O1P/O2P` atoms are created in the xyz file, but oddly despite most of the `CA` atom have all four bonds including the `HA` atom except near the end of the molecule or even the next `C` in the peptide bond won't have an atom connection to the previous `CA ` atom.  Examples below and PDB file [attached](https://drive.google.com/file/d/1s2uZ0gj9KQiPjZxd7khyoa4ELVO80mMm/view?usp=sharing).  

EDIT: it seems to be non-specific the type of connections that are missing after I test a few more times so the below is just type of bond missing. 

Latter `C` in next residue missing connection to previous `CA`.  Atom 4968 should connect back to 4953.
```
  4953  CA     8.88800000   16.79100000   51.99200000    64  4951  4954  4955  4968
  4954  HA     9.35900000   17.05800000   51.05800000    11  4953
  4955  CB     9.24200000   17.83500000   53.07000000    64  4953  4956  4957  4958
  4956  HB3   10.32400000   17.74400000   53.30100000    11  4955
  4957  HB2    8.65700000   17.60200000   53.98500000    11  4955
  4958  CG     8.95500000   19.29500000   52.67200000    64  4955  4959  4960  4964
  4959  HG     9.20500000   19.96300000   53.52400000    11  4958
  4960  CD1    9.78700000   19.70500000   51.44500000    64  4958  4961  4962  4963
  4961  HD1    9.41700000   19.17800000   50.54000000    11  4960
  4962  HD1   10.85300000   19.43300000   51.60300000    11  4960
  4963  HD1    9.70100000   20.80000000   51.27800000    11  4960
  4964  CD2    7.45100000   19.55900000   52.50800000    64  4958  4965  4966  4967
  4965  HD2    6.88200000   19.03200000   53.30300000    11  4964
  4966  HD2    7.10700000   19.18600000   51.51900000    11  4964
  4967  HD2    7.24700000   20.64800000   52.58900000    11  4964
  4968  C      9.43400000   15.48100000   52.48000000    62  4969  4970
```

**Comment by jayponder** [comment]
Hi Brian, I'm actually surprised you got that close... since Tinker's PDBXYZ is not set up to handle phosphorylated residues. As you say, it looks like there are two bonds where the connectivity is only one direction (ie, atom A is connected to atom B, but not the other way around). I'm guessing this might be due to the presence of the phosphates (?). Does PDBXYZ work completely correctly if you convert the PDB file of the protein without the phosphates? That said, your best option might be to just add the couple of missing bond connectivities to the XYZ file "manually".

**Comment by BJWiley233** [comment]
Yes I realized I could only get as far as running `xyzedit` on the files after manually adding the connections.  Realized tinker won't run any analysis on these files since the atom names are the PDB file atom names if you have a phosphorylated serine or any phosphorylated residues.  Thanks for confirming.  Any work coming down the pike for adding phosphorylated residues?

**Comment by jayponder** [comment]
Unfortunately, not that I know of at this time. There are two issues. First, we would have to extend the code for PDBXYZ, XYZPDB, etc. to know about and handle phosphorylated amino acids. This would be a bit of a pain if done "correctly", but not too terrible. The second, and perhaps bigger, issue would be getting good parameters for the modified amino acids in AMOEBA or whatever force field you want to use. I believe (not sure?) that none of the standard simpler force fields such as CHARMM, Amber and OPLS have standard or built-in parameters for phosphoamino acids. I know AMOEBA does not. Again, this would be a small, but nontrivial, research project to do this right.
