### ISSUE TITLE
Anisotropic Polarizability

### ISSUE THREAD

**Issue by subhajitdan** [TinkerTools/tinker#133]
How to use anisotropic polarizability for oxygen and hydrogen in  our simulation?

**Comment by jayponder** [comment]
The short answer is that Tinker does not support anisotropic atomic polarizabilities.

The polarizable force fields in Tinker (AMOEBA, AMOEBA+, HIPPO, etc.) all use damped polarization, such as the Thole model, that effectively provide anisotropic polarizability.
