### ISSUE TITLE
PDBXYZ assigns wrong atom types for N-terminal prolines that are not in the first chain

### ISSUE THREAD

**Issue by zjing7** [TinkerTools/tinker#141]
[NPRO.tgz](https://github.com/TinkerTools/tinker/files/12835517/NPRO.tgz)
When there is N-terminal proline in the second chain, PDBXYZ assigns atom type 59/60 to CD/HD, while the correct atom type should be 245/246 (all referring to amoebabio18). See the example attached.
I think this is related to Line 968-972 in pdbxyz.f 
```
c     proline residue  (PRO)
c
      else if (resname .eq. 'PRO') then
         call findatm (' CB ',start,stop,i)
         call oldatm (i,k,cai,ires)
         call findatm (' CG ',start,stop,i)
         call oldatm (i,k+2,n-1,ires)
         call findatm (' CD ',start,stop,i)
         if (ires .eq. 1) then
            call oldatm (i,469,n-1,ires)
         else
            call oldatm (i,k+4,n-1,ires)
         end if
```

**Comment by jayponder** [comment]
Thanks! This is now fixed and has been pushed to GitHub..
