### ISSUE TITLE
Error in printing solute keywords in key file

### ISSUE THREAD

**Issue by zjing7** [TinkerTools/tinker#143]
There is an error when running analyze with a key file that contains solute keywords
```
At line 180 of file /usr/local/tinker/source/ksolv.f (unit = 6, file = 'stdout')
Fortran runtime error: Expected INTEGER for item 5 in formatted transfer, got REAL
(6x,i6,7x,3f12.4)
    ^

```

https://github.com/TinkerTools/tinker/blob/7855bc814dc337a0e58e2495bf987d8019eafc05/source/ksolv.f#L181C43-L181C43

There are now four variables `pbrd,csrd,gkrd,snek`, but only three specifiers for floats `format (6x,i6,7x,3f12.4)`

**Comment by jayponder** [comment]
This is now fixed, and the patched version has been pushed to GitHub.
