### ISSUE TITLE
about tinker toturials

### ISSUE THREAD

**Issue by wyq87** [TinkerTools/tinker#146]
two website about tinker toturials cannot be opened:
https://biomol.bme.utexas.edu/tinkergpu/index.php?title=Tinkergpu:Tinker-tut
https://sites.google.com/site/biomolsimstw/workshop-materials/tutorials

**Comment by pren** [comment]
FYI:
https://github.com/TinkerTools/tinker-openmm
[https://opengraph.githubassets.com/576476bd3fc6a93102b10b133c638c97c3020ca691726013de48065bc606faf9/TinkerTools/tinker-openmm]<https://github.com/TinkerTools/tinker-openmm>
GitHub - TinkerTools/tinker-openmm: Tinker-OpenMM: Tinker Interface for OpenMM<https://github.com/TinkerTools/tinker-openmm>
Tinker-OpenMM: Tinker Interface for OpenMM. Contribute to TinkerTools/tinker-openmm development by creating an account on GitHub.
github.com

________________________________
From: Yiqiu Wang ***@***.***>
Sent: Tuesday, October 31, 2023 8:50 PM
To: TinkerTools/tinker ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TinkerTools/tinker] error occurred when compiling tinker-openmm (Issue #146)


When I used the command make -j to compile tinker-openmm, the error was reported:

ommdata.f:158:63:

       call set_polar_data (npolar,ipolar,polarity,thole,dirdamp,pdamp,
                                                               1
Error: Symbol ‘dirdamp’ at (1) has no IMPLICIT type; did you mean ‘pdamp’?
ommdata.f:169:49:

      &                      w4scale,w5scale,udiag,polprt,dpequal,
                                                 1
Error: Symbol ‘udiag’ at (1) has no IMPLICIT type; did you mean ‘udirp’?
ommdata.f:170:49:

      &                      use_thole,use_dirdamp,poltyp)
                                                 1
Error: Symbol ‘use_dirdamp’ at (1) has no IMPLICIT type; did you mean ‘use_disp’?
ommdata.f:174:68:

      &                      use_angtor,use_tortor,use_vdw,use_repuls,
                                                                    1
Error: Symbol ‘use_repuls’ at (1) has no IMPLICIT type; did you mean ‘use_repel’?
make: *** [ommdata.o] Error 1
make: *** Waiting for unfinished jobs....


Why?
My install environment is above:

TINKERDIR = $(HOME)/software/tinker-openmm
TINKER_LIBDIR = $(TINKERDIR)/lib
BINDIR = $(TINKERDIR)/bin
LINKDIR = /usr/local/bin

FFTWDIR = $(HOME)/software/tinker/fftw
FFTW_LIBDIR = -L$(FFTWDIR)/lib
FFTW_LIBS = -lfftw3_threads -lfftw3

OPENMMDIR = $(HOME)/software/openmm-7.5.0
OPENMM_INCLUDE = $(OPENMMDIR)/include
OPENMM_LIBDIR = -L$(OPENMMDIR)/lib
OPENMM_LIBS = -lOpenMM -lOpenMMAmoeba

CUDA_DIR = $(HOME)/software/cuda-11.4.1
CUDA_INCLUDE = $(CUDA_DIR)/include
CUDA_LIB = $(CUDA_DIR)/lib

# Uncomment below for 64-bit Linux only
CUDA_LIB = $(CUDA_DIR)/lib64
NVML_INCLUDE = $(CUDA_DIR)/include
NVML_LIB = $(CUDA_DIR)/lib64/stubs


Moreover,two website about tinker toturials cannot be opened:
https://biomol.bme.utexas.edu/tinkergpu/index.php?title=Tinkergpu:Tinker-tut
https://sites.google.com/site/biomolsimstw/workshop-materials/tutorials

**Comment by Cynthia0807-learn** [comment]
Thanks for your reply.I have read this link before installing tinker-openmm,so I install openmm-7.5.0(it was released in Dec 10, 2020,  prior to 4 march 2021). I will try older version.
