### ISSUE TITLE
Query regarding use of poledit

### ISSUE THREAD

**Issue by heman3333** [TinkerTools/tinker#147]
I am doing parameterization of a molecule. So in the process, we have to choose
polarization groups within the molecule while using 'poledit' command over gdmaout file.
What would be the specific command to do that, say, for Urea molecule ?

**Comment by jayponder** [comment]
POLEDIT has the user select from three options for setting polarization groups: (1) put all atoms into one group, (2) separate into groups at rotatable bonds, or (3) manual entry of the bonds that separate the molecule into groups.

For most cases, we recommend option (2), in which case POLEDIT will automatically separate the groups at bonds that freely rotate or at least rotate with low barriers at typical temperatures. This is the option we generally use for the AMOEBA or HIPPO force fields. For small organics, you can just use option (1) and put all atoms into a single polarization group. We do not suggest option (3) unless you have some specific reason for wanting to choose your own custom groups. Fortunately, in most cases, the choice of where to split the polarization groups should not have a big effect on the performance or results from the model.

**Comment by heman3333** [comment]
Thank you very much for the clarification.
