### ISSUE TITLE
Wrong atom type for terminal Gly in multiple chains

### ISSUE THREAD

**Issue by zjing7** [TinkerTools/tinker#148]
When there are two chains, one of the alpha Hs of the C-terminal GLY of the first chain and the N-terminal GLY of the second chain will be assigned non-terminal atom type by PDBXYZ. This bug affects amber99sb which has different types for terminal and non-terminal alpha H. 
See the attached example.
[Gly.tgz](https://github.com/TinkerTools/tinker/files/13834665/Gly.tgz)

This is similar to #141

**Comment by jayponder** [comment]
This is fixed. Sorry it took so long- I completely forgot about it, and just today noticed the issue again.. The GLY issue here and the PRO issue you found earlier are, I believe, the only problems of this type.
