### ISSUE TITLE
OPLSAA-M torsional parameters in oplsaam.prm file.

### ISSUE THREAD

**Issue by BernardUPSaclay** [TinkerTools/tinker#149]
I would like to use torsion parameters for the peptide backbone to model PBLG (poly gamma-benzyl L-glutamate). I compare data in the Robertson-2015-JCTC paper and the oplsaa.prm, oplsaal.prm and oplsaam.prm files of tinker 8.10.5 distribution. Although oplsaa and oplsaal parameters correspond to those in Robertson paper, I find that parameters given in oplsaam.prm are different from those given in Robertson-2015 but are identical to those in oplsaal.prm. 

E.g. the angle phi (C-N-Calpha-C) along the peptide backbone is described by the following atom CLASS (classes are different for oplsaa and oplsaa-l/m) :

```
file	    CLASS          V1/V2/V3                    V1/V2/V3
                          Robertson                   .prm files
-------------------------------------------------------------------------------
oplsaa    3-24-13-3    -2.365 / 0.912 / -0.85       -2.365 / 0.912 / -0.85
oplsaal  21-23-1-21    -0.596 / 0.279 / -4.913      -0.596 / 0.279 / -4.913
oplsaam  21-23-1-21    -2.511 / 0.21  / -0.200      -0.596 / 0.279 / -4.913

```

I find the same behavior for other angles along the peptide backbone.

Did I do some stupid mistake or misunderstood something in Robertson paper or tinker files organization? Or is there something wrong in the files?

**Comment by lukhman9020** [comment]
> I would like to use torsion parameters for the peptide backbone to model PBLG (poly gamma-benzyl L-glutamate). I compare data in the Robertson-2015-JCTC paper and the oplsaa.prm, oplsaal.prm and oplsaam.prm files of tinker 8.10.5 distribution. Although oplsaa and oplsaal parameters correspond to those in Robertson paper, I find that parameters given in oplsaam.prm are different from those given in Robertson-2015 but are identical to those in oplsaal.prm.
> 
> E.g. the angle phi (C-N-Calpha-C) along the peptide backbone is described by the following atom CLASS (classes are different for oplsaa and oplsaa-l/m) :
> 
> ```
> file	    CLASS          V1/V2/V3                    V1/V2/V3
>                           Robertson                   .prm files
> -------------------------------------------------------------------------------
> oplsaa    3-24-13-3    -2.365 / 0.912 / -0.85       -2.365 / 0.912 / -0.85
> oplsaal  21-23-1-21    -0.596 / 0.279 / -4.913      -0.596 / 0.279 / -4.913
> oplsaam  21-23-1-21    -2.511 / 0.21  / -0.200      -0.596 / 0.279 / -4.913
> ```
> 
> I find the same behavior for other angles along the peptide backbone.
> 
> Did I do some stupid mistake or misunderstood something in Robertson paper or tinker files organization? Or is there something wrong in the files?

Dear Sir,
I trust this message finds you well. I am reaching out to seek your guidance regarding the installation of TINKER on my Linux system. I have successfully installed the software, but I am uncertain about its correct installation and encounter issues when trying to execute it.
My specific goal is to utilize TINKER for quantum mechanics/molecular mechanics (QM/MM) calculations in the context of excited state dynamics within the SHARC-MOLCAS interface framework. Unfortunately, when attempting to provide the TINKER path in my input files, the execution fails.
Additionally, if you could provide details on how you installed TINKER on your computer and configured the path successfully, it would greatly assist me in resolving my issues.
I appreciate your time and expertise in advance. Your guidance will significantly contribute to my research endeavors.

Thank you and looking forward to your prompt response.

Thanks & Regards.
LUKHMANUL HAKEEM K.
IMS20172

**Comment by jayponder** [comment]
The OPLSAA-M parameters are something we were/are working on adding to Tinker. That file was never intended to be included in the GitHub release, as it was incomplete. It has been since been removed from the Tinker repo. Sorry for the confusion and inconvenience.
