### ISSUE TITLE
Facing issue in the energy minimization of small system

### ISSUE THREAD

**Issue by heman3333** [TinkerTools/tinker#150]
So I am doing some test on 64 water system in Tinker.  While doing the energy minimization, I am getting the following error:
'VLIST  --  Pairwise Neighbor List cannot be used with Replicas'.

When I turned off the 'mpole-list' or 'neighbor-list' term. then the energy minimization is going fine.

**Comment by jayponder** [comment]
Hi, What you are seeing is the expected/correct behavior of Tinker. A cube with 64 waters at ambient temperature and pressure would be something like 12.43 Ang on a side. The default cutoff for vdw interactions in Tinker is generally 9 Ang, while for electrostatics it is somewhere in the 7 to 9 Ang range. As per the warning and program termination you observed, the cutoff for electrostatics or for vdw cannot be greater than half of the minimal box dimension. So you need to remove the neighbor-list, vdw-list, mpole-list, etc. keywords when running calculations on a very small system like 64 waters.

The above is not an issue and is not a "bug". The only point to using interaction lists is to speed up the searching of neighbors when the system size is (significantly) larger than the cutoff distance. Even if you could use lists with a very small system like 64 waters, there would be zero speed advantage and calculations might in fact be slower.
