### ISSUE TITLE
Zn ion is not getting converted

### ISSUE THREAD

**Issue by mayank-kohli** [TinkerTools/tinker#151]
Hi,

I am trying to convert a protein PDB file to XYZ file, It has a Zinc ion in it but after I run the command in the output XYZ file there is no ZN ion.

Thank you

**Comment by jayponder** [comment]
Hi, There are two conditions that must be met for Tinker to translate an ion from a PDB file to a Tinker XYZ file. First, the force field you specify for the output XYZ file must contain parameters for the ion. Second, the "residue name" of the ion in the PDB file has to be something that Tinker recognizes as a valid ion name. For a zinc ion, Tinker recognizes ZN or ZN+ as zinc ion residue names.

If you think the above conditions are met and you are not getting the zinc ion in the XYZ file, then contact us. If you have an official PDB file with another name for the ion, we would also like to know. In either of these cases, please send the PDB code for the file in question, email it to ponder@dasher.wustl.edu, or post it here. In the meantime, it should not be hard for you to manually add the ion to your XYZ file.
