### ISSUE TITLE
analyze issue with TIP5P

### ISSUE THREAD

**Issue by mircodaniel** [TinkerTools/tinker#153]
When I use the tinker tool analyze with TIP5P water and particular molecule (e.g. acetic acid) I get some strange results.
My .xyz file looks like this:

  13 HAc_H2O
     1  C      0.441909    0.390814    0.078903     209     2     3     5
     2  O      1.548455    0.693361   -0.351452     210     1
     3  O     -0.165194    1.060171    1.090898     211     1     4
     4  H      0.403730    1.758478    1.373750     212     3
     5  C     -0.400224   -0.760146   -0.448740     80     1     6     7     8
     6  H     -0.597172   -1.480851    0.344606     85     5
     7  H     -1.351979   -0.390312   -0.829515     85     5
     8  H      0.120476   -1.271516   -1.258450     85     5
     9  O      2.940531    0.032590   -0.026181     73    10    11    12    13
    10  H      3.532313    0.352631    0.654700     74     9
    11  H      3.307364   -0.812787   -0.285031     74     9
    12  Lp     2.927421    0.473437   -0.569765     75     9
    13  Lp     2.292372   -0.045870    0.226277     75     9

Content of .key file:

PARAMETERS	"./oplsaa.prm"
DIELECTRIC	1.0
NONBONDTERM ONLY
OPENMP-THREADS 1

With analyze (program D for detail) I get following output:

 Individual Charge-Charge Interactions :

 Type              Atom Names                 Charges     Distance      Energy

 Charge          1-C       10-H             0.52   0.00     3.1438     13.2367
 Charge          1-C       11-H             0.52   0.24     3.1292     13.2985
 Charge          1-C       12-Lp            0.52   0.24     2.5701    -16.1916
 Charge          1-C       13-Lp            0.52  -0.24     1.9070    -21.8217
 Charge          2-O        4-H            -0.44   0.45     2.3283    -14.1190
 Charge          2-O        6-H            -0.44   0.06     3.1330     -1.3991
 Charge          2-O        7-H            -0.44   0.06     3.1330     -1.3991
 Charge          2-O        8-H            -0.44   0.06     2.5928     -1.6905
 Charge          2-O       10-H            -0.44   0.00     2.2504    -15.6471
 Charge          2-O       11-H            -0.44   0.24     2.3166    -15.1997
 Charge          2-O       12-Lp           -0.44   0.24     1.4134     24.9135
 Charge          2-O       13-Lp           -0.44  -0.24     1.1973     29.4080
 Charge          3-O        6-H            -0.53   0.06     2.6833     -1.9676
 Charge          3-O        7-H            -0.53   0.06     2.6833     -1.9676
 Charge          3-O        8-H            -0.53   0.06     3.3223     -1.5892
 Charge          3-O       10-H            -0.53   0.00     3.7898    -11.1917
 Charge          3-O       11-H            -0.53   0.24     4.1785    -10.1506
 Charge          3-O       12-Lp           -0.53   0.24     3.5590     11.9175
 Charge          3-O       13-Lp           -0.53  -0.24     2.8303     14.9858
 Charge          4-H        5-C             0.45  -0.18     3.2111     -4.1881
 Charge          4-H        6-H             0.45   0.06     3.5432      2.5304
 Charge          4-H        7-H             0.45   0.06     3.5432      2.5304
 Charge          4-H        8-H             0.45   0.06     4.0236      2.2282
 Charge          4-H       10-H             0.45   0.00     3.5045     10.2759
 Charge          4-H       11-H             0.45   0.24     4.2183      8.5371
 Charge          4-H       12-Lp            0.45   0.24     3.4348    -10.4845
 Charge          4-H       13-Lp            0.45  -0.24     2.8530    -12.6227
 Charge          5-C       10-H            -0.18   0.00     4.2333     -3.4027
 Charge          5-C       11-H            -0.18   0.24     3.7116     -3.8810
 Charge          5-C       12-Lp           -0.18   0.24     3.5510      4.0565
 Charge          5-C       13-Lp           -0.18  -0.24     2.8663      5.0255
 Charge          6-H       10-H             0.06   0.00     4.5288      1.0602
 Charge          6-H       11-H             0.06   0.24     4.0110      1.1971
 Charge          6-H       12-Lp            0.06   0.24     4.1326     -1.1619
 Charge          6-H       13-Lp            0.06  -0.24     3.2284     -1.4873
 Charge          7-H       10-H             0.06   0.00     5.1586      0.9308
 Charge          7-H       11-H             0.06   0.24     4.7100      1.0194
 Charge          7-H       12-Lp            0.06   0.24     4.3734     -1.0979
 Charge          7-H       13-Lp            0.06  -0.24     3.8098     -1.2603
 Charge          8-H       10-H             0.06   0.00     4.2354      1.1337
 Charge          8-H       11-H             0.06   0.24     3.3637      1.4275
 Charge          8-H       12-Lp            0.06   0.24     3.3761     -1.4222
 Charge          8-H       13-Lp            0.06  -0.24     2.9024     -1.6544

 Individual van der Waals Interactions :

 Type              Atom Names                    Minimum    Actual      Energy

 VDW-LJ          1-C        9-O                   3.8394    2.5264     16.4803
 VDW-LJ          2-O        6-H                   3.0534    3.1330     -0.0389
 VDW-LJ          2-O        7-H                   3.0534    3.1330     -0.0389
 VDW-LJ          2-O        8-H                   3.0534    2.5928      0.0707
 VDW-LJ          2-O        9-O                   3.4111    1.5749   1915.9830
 VDW-LJ          3-O        6-H                   3.0740    2.6833      0.0210
 VDW-LJ          3-O        7-H                   3.0740    2.6833      0.0210
 VDW-LJ          3-O        8-H                   3.0740    3.3223     -0.0308
 VDW-LJ          3-O        9-O                   3.4341    3.4568     -0.1647
 VDW-LJ          5-C        9-O                   3.7092    3.4594     -0.0750
 VDW-LJ          6-H        9-O                   3.1349    3.8657     -0.0338
 VDW-LJ          7-H        9-O                   3.1349    4.3875     -0.0172
 VDW-LJ          8-H        9-O                   3.1349    3.3424     -0.0622

 Intermolecular Energy :                1945.8568 Kcal/mole

 Total Potential Energy :               1924.8298 Kcal/mole

 Energy Component Breakdown :           Kcal/mole        Interactions

 Van der Waals                          1932.1145               13
 Charge-Charge                            -7.2847               43

As You can see there is no charge-charge interaction with 9-O and the VdW-energy of 2-O and 9-O is way too high. This happens with latest tinker version (windows version as well as linux version). It happens also when I take TIP5P water and DMP or MP, but not when I take TIP5P water and methanol.

**Comment by jayponder** [comment]
All I can say is that the xyz structure in your first message above is not reasonable- two nonbonded oxygens cannot get as close as 1.57 Ang. Your structure should have a very high vdw energy, just as it does. So I think the problem here is not with Tinker or the OPLS-AA parameters.
