### ISSUE TITLE
cation.run attempts to run the command 'bar' without the prefix ../bin/

### ISSUE THREAD

**Issue by yurivict** [TinkerTools/tinker#156]
In most or all other places commands are expected to be in ../bin/, but [here](https://github.com/TinkerTools/tinker/blob/release/test/cation.run#L7) it runs 'bar' without ../bin/.

These 'bar' commands fail because of this.

Version: 8.11.1
FreeBSD 14.0

**Comment by jayponder** [comment]
Hi, I just pushed this small fix to GitHub. Thanks for reporting.
