### ISSUE TITLE
Units of the polarizability tensor

### ISSUE THREAD

**Issue by FranklinHu1** [TinkerTools/tinker#160]
Hello,

I am using Tinker with the AMOEBA-2009 parameters to compute the polarizability tensor for a box of 64 water molecules and also to compute the molecular polarizability tensors by dividing the difference of the induced dipoles by the applied field strength. From looking at the source code in https://github.com/TinkerTools/tinker/blob/release/source/polar.f, the comment states that the dipole polarizability for each atom site is given in Angstrom^3. I have two questions:

1. Does this mean that the polarizability tensor produced at the end of the output file is also in units of Angstrom^3? 
2. If I parse the induced dipoles from the output file (in Debye) and convert them back to eA before dividing the dipole difference by the electric field, does this also return units of Angstrom^3?

Any help would be greatly appreciated. 

Thank you very much!

Frank

**Comment by jayponder** [comment]
Hi, Sorry that this apparently dropped through the cracks for a very long time! As you have probably figured out, the answer to your first question is definitely "yes". And I believe the answer to the second is "yes" as well. Please post a new issue if you have any further questions or comments.
