### ISSUE TITLE
'readgau' can not function

### ISSUE THREAD

**Issue by ru80john** [TinkerTools/tinker#162]
Hello,

I'm using the command called 'valence' which is one of the Tinker parameterization tools and I encountered the issue shown below: 
```   
   ######################################################################
   ##########################################################################
  ###                                                                      ###
 ###            Tinker  ---  Software Tools for Molecular Design            ###
 ##                                                                          ##
 ##                       Version 8.11.4  October 2024                       ##
 ##                                                                          ##
 ##               Copyright (c)  Jay William Ponder  1990-2024               ##
 ###                           All Rights Reserved                          ###
  ###                                                                      ###
   ##########################################################################
     ######################################################################


 The Tinker Valence Parameter Utility Can :

    (1) Set Initial Values for Valence Parameters
    (2) Compare QM and MM Vibrational Frequencies
    (3) Force Fit of Parameters to QM Results
    (4) Structure Fit of Parameters to QM Results

 Enter the Number of the Desired Choice :  3

 Enter Cartesian Coordinate File Name :  out.xyz

 Enter the Gaussian Output File Name :  test.log
At line 148 of file readgau.f
Fortran runtime error: Index '21' of dimension 1 of array 'gx' above upper bound of 20

Error termination. Backtrace:
#0  0x7f562b040171 in ???
#1  0x7f562b040d19 in ???
#2  0x7f562b0410fb in ???
#3  0x506175 in ???
#4  0x42347f in ???
#5  0x4240c7 in ???
#6  0x7f562a6d3ca2 in ???
#7  0x4016cd in ???
#8  0xffffffffffffffff in ???
```
The error looks like the number of atoms in Gaussian output is not equal to the .xyz file, but I've checked that the number is the same.
 
Are there other possibilities that could cause this problem?

Any help would be greatly appreciated.

Thank you very much!

John

**Comment by jayponder** [comment]
Hi, If you can post here your Gaussian file ("test.log") and the corresponding Tinker XYZ file ("out.xyz"), then I can take a look to see if I can find the issue.

That said, we do not recommend use of the VALENCE program in Tinker. It's use is mostly obsolete, and is largely replaced by the various automated parameter generation programs for several different force fields. For example, the Poltype package (available on GitHub at the TinkerTools organization) will generate AMOEBA force field parameters for arbitrary input organic molecules. The LigParGen package available on Bill Jorgensen's website at Yale will generate OPLS-AA parameters, and can write Tinker compatible files. And the GAFF/2 and CGENFF packages can generate parameters for Amber and CHARMM force fields, respectively. Though the latter two packages do not write their parameters in Tinker format, so you would need to convert their output to use it with Tinker.

**Comment by ru80john** [comment]
I see. 

I've recently noticed the Poltype package for AMOEBA force field, I'll try that first.
Thanks for your advice! 

And file 'out.xyz' and test.log are listed below.

John

out.xyz
```
    20
     1  C      1.888570   -0.936900   -0.040320     1     2     5     7
     2  O      0.674240   -1.375960    0.409140     2     1     3
     3  C     -0.196950   -0.247570    0.639790     3     2     4     6    12
     4  C      0.653860    0.946580    0.301620     4     3     5    10
     5  C      1.855660    0.522670   -0.106900     5     1     4     8
     6  H     -0.453700   -0.250770    1.706980     6     3
     7  O      2.811990   -1.657900   -0.315470     7     1
     8  O      2.913480    1.266620   -0.502520     8     5     9
     9  H      3.638040    0.660190   -0.715840     9     8
    10  O      0.168090    2.193760    0.449020    10     4    11
    11  H      0.845480    2.836090    0.199230    11    10
    12  C     -1.470180   -0.409100   -0.198930    12     3    13    14    16
    13  H     -1.197010   -0.407240   -1.257030    13    12
    14  O     -2.080590   -1.680950    0.023110    14    12    15
    15  H     -2.058200   -1.895310    0.962920    15    14
    16  C     -2.500020    0.692750    0.063490    16    12    17    18    19
    17  H     -2.109220    1.670120   -0.215880    17    16
    18  H     -2.737270    0.716100    1.139410    18    16
    19  O     -3.665740    0.470260   -0.707190    19    16    20
    20  H     -3.885520   -0.466300   -0.621010    20    19
```
[test.log](https://github.com/user-attachments/files/17956949/test.log)

**Comment by jayponder** [comment]
I have fixed this bug, and pushed the fix to GitHub. However using the VALENCE program to try to "force fit" parameter values requires an initiail set of parameters read from an existing parameter file, which will then be refined by force fitting. So I still recommend that you try to use the Poledit program, and I see you posted a question in that forum. I'll let the Poltype folks answer you there. Poltype is rather complex and has a fairly steep learning curve, however it is the best general method to get AMOEBA parameters.
