### ISSUE TITLE
trudge.f lot of errors

### ISSUE THREAD

**Issue by amrhamedp** [TinkerTools/Tinker#35]
Hello, can you please check simplex minimizer trudge.f
I think it has a lot of errors since very old releases even in the last version. The obvious ones are related to xx size being a 1D array instead of 2D array and its allocation..

In fact it seems incomplete......lot of non allocated variables , missing assignment of variables like eps

**Comment by jayponder** [comment]
The code cited, trudge.f, is a simplex optimization routine found in the /other directory of the distribution. The /other directory distributed with Tinker contains old, unused routines or incomplete demonstration codes. None of this code is used as part of the main Tinker distribution, and in most cases it is not updated to maintain compatibility with current releases. They are provided simply as a historical record and in the hope that someone who needs one of those routines might be willing to update it for use with current Tinker or some other project.
