### ISSUE TITLE
Tinker installation in linux system

### ISSUE THREAD

**Issue by DDGmichigan** [TinkerTools/Tinker#45]
Hi,
I have downloaded the latest version of TINKER ( Tinker Complete Distribution (ZIP, 44.5 Mb))
Following instructions of Christoph J. given in the configure folder, I did these steps

copy configure.ac and Makefile.am to the source folder
cd ../source
autoreconf -i -v
./configure
5 make
The steps seem okay till ./configure

However when I type make, I get the following error. please help

[source]$ make
/bin/sh ./libtool --tag=F77 --mode=compile gfortran -g -O2 -c -o action.lo action.f
libtool: compile: gfortran -g -O2 -c action.f -fPIC -o .libs/action.o
libtool: compile: gfortran -g -O2 -c action.f -o action.o >/dev/null 2>&1
/bin/sh ./libtool --tag=F77 --mode=compile gfortran -g -O2 -c -o active.lo active.f
libtool: compile: gfortran -g -O2 -c active.f -fPIC -o .libs/active.o
active.f:20.9:

  use atoms
     1
Fatal Error: Can't open module file 'atoms.mod' for reading at (1): No such file or directory
make: *** [active.lo] Error 1

**Comment by jayponder** [comment]
We will try to fix the configure scripts across all platforms for the next major release. In the meantime, please just use the provided Makefile, which requires only very minor editing near the top of the file to work on Linux, MacOS and Windows with GNU gcc/gfortran and other compilers.
