### ISSUE TITLE
Tinker-OpenMM non-orthogonal boxes

### ISSUE THREAD

**Issue by zjing7** [TinkerTools/Tinker#46]
Tinker-OpenMM can correctly read non-orthogonal box dimensions from xyz file and run simulations, but when writing dyn and arc files, it incorrectly takes the diagonal components of the box vector as the lattice parameters [a, b, c]. Because the coordinates are move into the wrong (smaller) box, this causes overlap between atoms.
For example, with input lattice parameters:
`117.9256  117.9256  117.9256  109.471219  109.471219  109.471219`
the box vectors in the dynamic_omm output are
```
Box Vectors:      117.9256       0.0000       0.0000
  (Ang)          -39.3085     111.1813       0.0000
                 -39.3085     -55.5906      96.2858
```

The lattice parameters in the arc and dyn files become
`117.9256 111.1813  96.2858 109.471219  109.471219  109.471219`

**Comment by jayponder** [comment]
This was a bug in the ommstuf.cpp interface code. It is now fixed. As noted in the original comment, the OpenMM trajectory was computed correctly, but the wrong box size was sent back to Tinker for output to the .arc and .dyn files.
