### ISSUE TITLE
OPLSAA atomtypes from pdbxyz

### ISSUE THREAD

**Issue by S0S-90** [TinkerTools/Tinker#47]
When applying pdbxyz with the forcefield oplsaa.prm some of the atomtypes don't seem to fit perfectly:
* In amino acid isoleucine the C atom of the CH2 group gets atomtype 80 ("Alkane CH3-") whereas the C atom of the neighboring CH3 group gets atomtype 81 ("Alkane -CH2-"). Shouldn't it be the other way round?
* In lysine the C atom of the CH2 group which is next to the NH3+ receives atomtype 235 ("CH3NH3+"). Shouldn't atomtype 236 ("RCH2NH3+") be assigned instead?
* In N-terminal proline the C_delta atom gets atomtype 187 ("PRO CD") although atomtype 239 ("N-Terminal PRO CD") is exclusively for this purpose.

**Comment by ponderlab** [comment]
The ILE CG1 and CG2 was incorrect as noted, and has been fixed. The PRO CD was independently fixed, and is correct in the current version. For LYS CE, type 235 is correct despite the fact that the descriptive string the parameter file appears incorrect; use of type 236 at this position leads to the wrong total charge on the residue.

**Comment by jayponder** [comment]
The ILE CG1 and CG2 was incorrect as noted, and has been fixed. The PRO CD was independently fixed, and is correct in the current version. For LYS CE, type 235 is correct despite the fact that the descriptive string the parameter file appears incorrect; use of type 236 at this position leads to the wrong total charge on the residue.

**Comment by S0S-90** [comment]
Thank you very much for your reply. With the newest version of tinker (pulling directly from github) I could get the correct atomtypes for Ile and I know now that Lys is also correct. But I don't get atomtype 239 for any N-terminal proline. I tried with structures 3TWK and 1EE8 from the protein data bank (http://www.rcsb.org/) but it doesn't work.

When applying pdbxyz to 1EE8 I get a very strange structure for the N-terminal proline in chain A (see picture: obviously one C atom is converted into an H). 
![Unbenannt](https://user-images.githubusercontent.com/21076804/60025369-c3c2d880-9699-11e9-8df9-0a221da2ce60.png)

In chain B the atomic structure seems correct but the atomtype is still 187 instead of 239.
