### ISSUE TITLE
[regression] Version 8.7.1 fails to link: undefined reference to `dfftw_init_threads_', etc

### ISSUE THREAD

**Issue by yurivict** [TinkerTools/Tinker#50]
```
fftw/lib diffuse.o libtinker.a -lfftw3_threads -lfftw3 ; strip diffuse.x
/usr/local/bin/ld: libtinker.a(/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftsetup_':
fft3d.f:(.text+0x370): undefined reference to `dfftw_init_threads_'
/usr/local/bin/ld: fft3d.f:(.text+0x37c): undefined reference to `dfftw_plan_with_nthreads_'
/usr/local/bin/ld: fft3d.f:(.text+0x3a8): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: fft3d.f:(.text+0x3d4): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftclose_':
fft3d.f:(.text+0xe7e): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: fft3d.f:(.text+0xe8a): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftfront_':
fft3d.f:(.text+0x921): undefined reference to `dfftw_execute_dft_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftback_':
fft3d.f:(.text+0xe21): undefined reference to `dfftw_execute_dft_'
collect2: error: ld returned 1 exit status
fft3d.o): in function `fftsetup_':
fft3d.f:(.text+0x370): undefined reference to `dfftw_init_threads_'
/usr/local/bin/ld: fft3d.f:(.text+0x37c): undefined reference to `dfftw_plan_with_nthreads_'
/usr/local/bin/ld: fft3d.f:(.text+0x3a8): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: fft3d.f:(.text+0x3d4): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftclose_':
fft3d.f:(.text+0xe7e): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: fft3d.f:(.text+0xe8a): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftfront_':
fft3d.f:(.text+0x921): undefined reference to `dfftw_execute_dft_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftback_':
fft3d.f:(.text+0xe21): undefined reference to `dfftw_execute_dft_'
collect2: error: ld returned 1 exit status
strip: strip: open archive.x failed: No such file or directory
open correlate.x failed: No such file or directory
gmake[2]: *** [/usr/ports/science/tinker/work/tinker/make/Makefile:792: archive.x] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [/usr/ports/science/tinker/work/tinker/make/Makefile:792: correlate.x] Error 1
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftsetup_':
fft3d.f:(.text+0x370): undefined reference to `dfftw_init_threads_'
/usr/local/bin/ld: fft3d.f:(.text+0x37c): undefined reference to `dfftw_plan_with_nthreads_'
/usr/local/bin/ld: fft3d.f:(.text+0x3a8): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: fft3d.f:(.text+0x3d4): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftclose_':
fft3d.f:(.text+0xe7e): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: fft3d.f:(.text+0xe8a): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftfront_':
fft3d.f:(.text+0x921): undefined reference to `dfftw_execute_dft_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftback_':
fft3d.f:(.text+0xe21): undefined reference to `dfftw_execute_dft_'
collect2: error: ld returned 1 exit status
strip: open diffuse.x failed: No such file or directory
gmake[2]: *** [/usr/ports/science/tinker/work/tinker/make/Makefile:792: diffuse.x] Error 1
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftsetup_':
fft3d.f:(.text+0x370): undefined reference to `dfftw_init_threads_'
/usr/local/bin/ld: fft3d.f:(.text+0x37c): undefined reference to `dfftw_plan_with_nthreads_'
/usr/local/bin/ld: fft3d.f:(.text+0x3a8): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: fft3d.f:(.text+0x3d4): undefined reference to `dfftw_plan_dft_3d_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftclose_':
fft3d.f:(.text+0xe7e): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: fft3d.f:(.text+0xe8a): undefined reference to `dfftw_destroy_plan_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftfront_':
fft3d.f:(.text+0x921): undefined reference to `dfftw_execute_dft_'
/usr/local/bin/ld: libtinker.a(fft3d.o): in function `fftback_':
fft3d.f:(.text+0xe21): undefined reference to `dfftw_execute_dft_'
```

Found this problem while trying to update the FreeBSD port.
FreeBSD 12
```8.6.1``` didn't have this problem.
It seems that ```-lfftw3``` is  missing.

**Comment by zhi-wang** [comment]
Disclaimer: Not sure if it is FreeBSD related and not a FreeBSD user here.

I haven't found anything weird in the Makefile based on your report. It did include "-lfftw3_threads -lfftw3" flags and did not complain about not being able to find the FFTW libraries.

I suspect that the FFTW libraries that were actually used in the linking did not have these missing symbols. I'm curious about the result if you can run `nm -n libfftw3.a  | grep fftw_plan_dft_3d_`

**Comment by yurivict** [comment]
Normally everything is linked to shared libraries.

In any case, this symbol is present in the static library:
```
$ nm -n /usr/local/lib/libfftw3.a | grep fftw_plan_dft_3d_
00000000000003d0 T dfftw_plan_dft_3d_
```

**Comment by zhi-wang** [comment]
Would you upload your (maybe modified) Makefile here (drag and drop the Makefile in the message box), and specify the git commit hash? I'll take a look.

**Comment by yurivict** [comment]
Do you mean the port's Makefile?

**Comment by zhi-wang** [comment]
Whatever it was when you tried to compile it.

**Comment by zhi-wang** [comment]
I just downloaded a FreeBSD 12.0 virtual disk image and GCC/GMAKE toolchain, compiled FFTW-3.3.8 and the most recent Tinker commit but could not confirm the problem you have seen.

I still suspect that the problem is either in the way FFTW libraries were configured/installed or in the linking part of the Makefile.

**Comment by yurivict** [comment]
No,you need to update the top-level makefile:
Set ```DISTVERSION=	8.7.1``` as a version in ```Makefile```, and run the command 'make makesum'.
Then run 'make' and observe the problem.

**Comment by yurivict** [comment]
I uploaded the tarball of the whole failed build directory: https://people.freebsd.org/~yuri/tinker-build.tgz

**Comment by zhi-wang** [comment]
Aha, l can confirm your problem and let me backtrace its origin.

The typical error will appear after this command, for example, `gfortran -Ofast -msse -msse2 -mfpmath=sse -fopenmp -static-libgcc -o alchemy.x -L. -L/usr/home/zw/port/tinker/work/tinker/lib/macos -L/usr/home/zw/port/tinker/work/tinker/fftw/lib alchemy.o libtinker.a -lfftw3_threads -lfftw3 ; strip alchemy.x`

There are two problems in the command above:
(1) The directory `tinker/fftw/lib` has been removed from the release some time ago but it was kept in the Makefile, which is not a big deal because gmake won't complain about the missing directory after the `-L` flag;
(2) The directory `tinker/lib/macos` was kept in the Makefile -- if you take a look, it contains several prebuilt fftw3 libraries and these are the actual fftw3 libraries used in the linking, which are of course, incompatible with the FreeBSD system.

I noticed that someone made changes to `work/tinker/make/Makefile` to adopt `PORT_SIMD_FLAGS` and `BSD_INSTALL_PROGRAM`. Obviously, the Port maintainer noticed the comments near line 60:
> Known Machine Types; Uncomment One of the Following Sections
> May Need Editing to Match Your Desired OS & Compiler Version

but forgot to remove `-L$(TINKER_LIBDIR)/macos` from `LIBDIR = -L. -L$(TINKER_LIBDIR)/macos` in line 89.

**Comment by yurivict** [comment]
It's the patch ```files/patch-make_Makefile``` that is doing this.

BTW, you should use the ```install``` command to install things, not ```mv```.

And SIMD flags should better be configurable from outside, like
```SIMD_FLAGS?=-ssse3```

**Comment by yurivict** [comment]
> but forgot to remove -L$(TINKER_LIBDIR)/macos from LIBDIR = -L. -L$(TINKER_LIBDIR)/macos in line 89.

This solves the problem, thanks!
I've just updated the port.

**Comment by zhi-wang** [comment]
I'll notice @jayponder to consider your suggestions. Thanks.
