### ISSUE TITLE
"repulsionterm only" gives zero energy and forces for periodic systems

### ISSUE THREAD

**Issue by JoshRackers** [TinkerTools/Tinker#62]
I believe this is an issue with handling the multipoles, but I am not sure. If you add "multipoleterm" after the "repulsionterm only" line, the energy and forces are correct. Looking into it.

**Comment by jayponder** [comment]
Hi Josh, I don't see this issue with a periodic HIPPO water box using the current/latest code. REPULSIONTERM ONLY gives the right value from the ANALYZE program, and from TESTGRAD as well. Post or send the system where you are getting incorrect behavior.

**Comment by JoshRackers** [comment]
Here's a minimal system that reproduces the error:
1. watersmall.xyz from examples
2. water19.prm from params
3. The following key file
`parameters        ./water19
verbose

a-axis                       18.643

neighbor-list
list-buffer                     0.1

repulsionterm only`

And run the command:
~/codes/Tinker/source/testgrad.x watersmall.xyz y n n 

Let me know if you are able to reproduce.

**Comment by JoshRackers** [comment]
Well, my Tinker wasn't that old. My clone was from October, I think. But you are correct. I pulled in the most recent changes to release, and the error no longer appears!
