### ISSUE TITLE
pdbxyz cannot handle single amino acid

### ISSUE THREAD

**Issue by walkerbdev** [TinkerTools/tinker#65]
[pdbxyzoutput.txt](https://github.com/TinkerTools/tinker/files/5351147/pdbxyzoutput.txt)
[isolecuine.txt](https://github.com/TinkerTools/tinker/files/5351149/isolecuine.txt)

Hello, 

When I attempt to use a single amino acid, pdbxyz throws in error (above in pdbxyzoutput.txt), however when I use two Isolecuines (built via pymol then convert to correct atom labels via babel) then pdbxyz works fine.

- Brandon

**Comment by jayponder** [comment]
Hi Brandon, This is sort of a "known problem". PDBXYZ does not handle single amino acid zwitterions. And the AMOEBA protein force fields are not parameterized for single amino acid zwitterions. Note that capped single amino acids, like "alanine dipeptide" are fine in PDBXYZ and also have parameters in the force fields.

I'll take a look and get PDBXYZ to do something more graceful for single amino acids. What you report in your attached "pdbxyzoutput.txt" file is rightly a "bug"... But unless we add single amino acid zwitterion parameters to the AMOEBA parameter files, you will not get an XYZ file that you can actually use in calculations.

**Comment by bdw2292** [comment]
Ah okay, I just wanted to be able to distinguish between which carbon atom
was Isolecine CG1 and CG2, its not a huge issue since I can make peptide
with several amino acids.

**Comment by bdw2292** [comment]
In other words, there is some convention in the prm file, I just did not
know without applying pdbxyz.

**Comment by jayponder** [comment]
I've fixed the bug in PDBXYZ. So it will now run "correctly" for a single amino acid PDB file and generate an XYZ file. But many of the protein force fields (AMOEBA versions, in particular) do not have parameters for single amino acid zwitterions, so the XYZ file produced by PDBXYZ can't be used in calculations.

It may be possible to make further modifications to PDBXYZ that will assign more reasonable atom types for single amino acid systems, and I'll try to look into this.
