### ISSUE TITLE
MM3PRO Hessian

### ISSUE THREAD

**Issue by NF-AMU** [TinkerTools/tinker#74]
Hi, 
While using the enkephalin example which is based on the MM3pro ff, I've experienced that the numerical and analytical Hessian elements can differ much. For instance:
 Comparison of Analytical and Numerical Hessian Elements :
   1st Atom    2nd Atom         Analytical        Numerical       Difference
...
     16 (Y)      16 (Y)             5.8317         -14.3572          20.1889
     16 (Y)      16 (Z)            17.6193          21.9278          -4.3085
     16 (Y)      23 (X)            51.6569          46.2261           5.4308
     16 (Y)      23 (Y)            45.3146          57.9164         -12.6018
     16 (Y)      23 (Z)            -0.5540          -3.0916           2.5375
...
in a calculation with van der Waals interactions only.

**Comment by jayponder** [comment]
Hi,

You are correct. The Tinker code does not have the exact analytical Hessian for the MM3PRO force field, as it uses an odd formulation including a hydrogen bond term for which we do not have the analytical Hessian. The H-bond modification makes the correct analytical Hessian really nasty. The "analytical" result printed by the TESTHESS program uses the standard MM3 vdw Hessian, without the hydrogen bonding modification. The numerical Hessian should be the "correct" Hessian value for MM3PRO.

I'm not sure we will fix this anytime soon, and I'm going to go ahead and close the issue. What I might do is print a warning for the MM3PRO case that the "analytical" Hessian is only approximate. The MM3PRO force field is essentially obsolete anyway, and is really only included in Tinker for historical reasons. If you want to model proteins you should switch to one the standard "biomolecular" force fields such as CHARMM, Amber or OPLS. Or you could use our polarizable AMOEBA force field if you want a more advanced, but slower.., model.
