### ISSUE TITLE
Poledit issue with Phosphric acid 

### ISSUE THREAD

**Issue by walkerbdev** [TinkerTools/tinker#77]
Hi Dr. Ponder,
We seem to have found an issue with current poledit.x file. There is a poor RMSPD shown in KeyOut.txt (at the bottom). The issue was compounded when we averaged the multipoles. Tinker 8.7 seems to provide reasonable results.

[AveragedKeyOut.txt](https://github.com/TinkerTools/tinker/files/5711506/AveragedKeyOut.txt)
[Phosphoricacid.pot.txt](https://github.com/TinkerTools/tinker/files/5711507/Phosphoricacid.pot.txt)
[Phosphoricacid_oldpoledit.txt](https://github.com/TinkerTools/tinker/files/5711508/Phosphoricacid_oldpoledit.txt)
[CorrectOutput.txt](https://github.com/TinkerTools/tinker/files/5711509/CorrectOutput.txt)
[Phosphoricacid.key.txt](https://github.com/TinkerTools/tinker/files/5711510/Phosphoricacid.key.txt)
[Phosphoricacid.key_2.txt](https://github.com/TinkerTools/tinker/files/5711511/Phosphoricacid.key_2.txt)
[KeyOut.txt](https://github.com/TinkerTools/tinker/files/5711512/KeyOut.txt)
[Phosphoricacid.xyz_2.txt](https://github.com/TinkerTools/tinker/files/5711513/Phosphoricacid.xyz_2.txt)

Commands and output are in KeyOut.txt and AveratedKeyOut.txt , the correct output is in CorrectOutput.txt using older tinker version (like 8.7 something).

Thanks for your time!

- Brandon

**Comment by pren** [comment]
This is not due to POLEDIT. The issue is with our own average script.

**Comment by bdw2292** [comment]
Correction, I was comparing 8.8 (which i called correct but that label may
not be appropriate) and 8.8.7. The latest poledit has frames on atom P
repeated twice ( I guess not huge deal).

**Comment by bdw2292** [comment]
Actually we found bug in how poltype parses and it was not expecting empty spaces on frame definition (it undersands 0 to mean empty atom in frame definition).
