### ISSUE TITLE
Activating an atom with i > n

### ISSUE THREAD

**Issue by NF-AMU** [TinkerTools/tinker#94]
Hi,

When, by mistake (!), the ACTIVE keyword is used with an atom number larger than the total number of atoms, n, Tinker activates the nth atom, even if this last atom is intended to be inactive. In the attached archive, the second logfile (waterdimer.out2) shows this behavior.
[active.zip](https://github.com/TinkerTools/tinker/files/7115276/active.zip)

Of course, this case is a true user error. However, I suppose it is worth including a test in active.f that would check that ACTIVE atom numbers stay <= n.

Nicolas

**Comment by jayponder** [comment]
Yes, that is bad behavior... Thanks for reporting it.

I've just put in a simple fix into the master Github repo. Now when an "illegal" atom number entry is found in the ACTIVE or INACTIVE lists, the program will not process that entry or any further entries. It also prints a warning message.

One could go much further and use a full parsing mechanism to protect the user against all sorts of incorrect input for this and other similar keywords. I prefer not to move in that direction, as it's impossible to protect against all illegal or incorrect inputs.
