### ISSUE TITLE
Hydrogen positions converting PDB to XYZ

### ISSUE THREAD

**Issue by peastman** [TinkerTools/tinker#95]
I have a PDB file I need to convert to XYZ so I can use it with Tinker.  (I'm working on amoebabio18 support in OpenMM, so I need to be able to compute forces and energies with both programs to compare.)  When I run pdbxyz on it, I find that all the heavy atoms get translated correctly, but all the hydrogens end up with entirely new positions.  Is there some way I can get it to translate the file accurately?

**Comment by peastman** [comment]
Here's another case I ran into.  In this file, atom 24 (H) doesn't get converted correctly.  But its name is completely standard.

[bpti2.pdb.txt](https://github.com/TinkerTools/tinker/files/7383361/bpti2.pdb.txt)

**Comment by jayponder** [comment]
I've fixed both the BPTI and DNA examples you posted just above. The fix is pushed to the Github release branch.

Thanks! This has been very helpful. By all means send any other cases you find... Hopefully this may be most, if not all, of them.
