### ISSUE TITLE
Missing istep in anneal.f

### ISSUE THREAD

**Issue by NF-AMU** [TinkerTools/tinker#96]
Hi,
In anneal.f, a couple of "istep" are missing in the arguments of several routines, between lines 288 and 306. Sorry, I can't submit a pull request. For a reason I don't undestand, my tinker clone does not appear in the list.
Best regards,
Nicolas

**Comment by jayponder** [comment]
Indeed, that's bad... We just made some simple changes around this, yesterday (!), while working on the interface to Tinker9. And as you note, we missed adding "istep" back in part of "anneal". It's fixed now. Thanks for finding and reporting this so quickly, and we're sorry for the bother.
